### PR TITLE
Submodules

### PR DESCRIPTION
**Pull request by Andr3as**
Implements submodules:

### Handling
```
GIT REPO
|--.git
|--libs
```
1. Right click to add submodule beyond `libs`

2. Enter path of submodule repository and directory name

```
GIT REPO
|--.git
|--libs
     |--CodeGit
```

3. Commit submodule
4. To perform git actions on the submodule open CodeGit on the submodule (right click on the submodule)

### CODE REVIEW

**Comment by viharm** [comment]
@Andr3as , in the absence of authentication, do you imply that submodules from repos which are protected/private cannot be added?

**Comment by Andr3as** [comment]
Yes, currently. I'll change this next week.

**Comment by viharm** [comment]
Sounds good, thanks.

How will the functionality to update submodules in existing repos work?

**Comment by viharm** [comment]
Hi @Andr3as . I would like to volunteer to test different use cases. Here are my proposed test scenarios:

1. Codiad environments
    1. Project root directory is a git repo.
    1. Project root directory is a regular directory, but a sub-directory is a git repo.
1. CodeGit test cases (for all environments list above)
     1. Clone a remote git repo with pre-existing submodules (more than one level of recursion). Example https://gitlab.com/viharm/Odux.git
     1. Add submodule to an existing local repo; then push to remote.

I am trying to test 2.ii, but cannot seem to get the `Add submodule` option in the context menu, as shown in your screenshots above. I have checked out the `Submodules` branch with HEAD at 39db63b42691b699babae61788039843b8ee3d5d. What am I doing wrong?

If I click on a sub-directory in the project, I get the two regular *CodeGit* options of `Git Init` and `Git Clone`.

Do I need to create a placeholder directory for the submodule to be added? Or will *CodeGit* do it for me?

**Comment by Andr3as** [comment]
Hi @viharm, that would be great, thank you.

The current plan is to open CodeGit on the submodule repo, perform your actions (pull, commit, etc.) and to reopen CodeGit on the parent repo to commit your changes on the submodule.

That's odd. Do you still have these problems?
No you don't need to create a placeholder directory, CodeGit creates the directory.

**Comment by viharm** [comment]
Sorry for the delayed response. Doing more things concurrently than I can handle :-P

I will test and provide feedback.

**Comment by viharm** [comment]
Hi @Andr3as , I have done preliminary testing on the submodule functionality. The following combinations work.

    * 1i / 2ii
    * 1ii / 2i
    * 1ii / 2ii

Unfortunately there is no option to initialise pre-existing submodules when creating a new projectd/workspace from a Git repo.

Hope this feedback helps.

**Comment by Andr3as** [comment]
Thanks a lot. I already thought about that. 1c9b097 should solve this.

Initialise existing submodules through the context menu on the `.submodules` file.


#### Todo: create a documentation

**Comment by viharm** [comment]
Hi @Andr3as,

Sorry for not being able to give feedback any earlier. Was moving house :-(

I have tested 1851cc4dd207ce4d04a7a04e30343664c7cbc189 with the following scenario combinations
*  1i - 2i : No option to update/initialise submodules when adding a new project directly by cloning a remote git repo.
*  1i - 2ii : Works as explained by you, commit and push submodule first, then the parent repo.
*  1ii - 2i : Works as expected, when cloning a remote repo to a new sub-directory. Codegit gives an option to initialise submodules. Works up to two levels of recursion and initialises submodules of submodules
*  1ii - 2ii: Works as explained by you, commit and push submodule first, then the parent repo.

Thank you very much for your efforts on this.

**Comment by Andr3as** [comment]
Thanks for your tests.

CodeGit is not part of the "create project"-dialog, the git clone option there is a direct part of Codiad.

dialog



The best way to achive this would be to create the project and clone the git repo afterwards.

**Comment by viharm** [comment]
@Andr3as , good point. Agreed :-)

**Pull request merged**
