### PR TITLE
Add support to lock down user for git commit to login via config

### PR DESCRIPTION
**Pull request by deitch**
Enables a config file `data/config/git.php` to have a parameter `lockuser`, which, if set to `true`, forces the git commit username to be identical to the Codiad login name

### CODE REVIEW

**Comment by Andr3as** [comment]
I'll merge it with #28 and #27 to version 0.6.0.

Before that, I have some comments:
- Please fix the whitespace
- Change the filename to `git.settings.php`  
(I use the following structure for other plugins to name config files:
    - User config: `PLUGIN.USER.php` for user specific settings
    - General config: `PLUGIN.settings.php` for general plugin settings)
- Update the code to match the changes of #27

**Comment by deitch** [comment]
> * Please fix the whitespace

Can you be specific? What issue is there with the whitespace?

> * Change the filename to `git.settings.php`

Done

* Update the code to match the changes of #27 

Is that 0.6.0? 

That is hard. Best process is the standard github process. If you merge 0.6.0 into master, it will cause this PR to fall out of sync. Then I can fix this to be in sync with master.

**Comment by Andr3as** [comment]
> Whitespace

f.e. [here](https://github.com/deitch/Codiad-CodeGit/blob/lock-down-git-user/controller.php#L307-L312)

>  - Change the filename to git.settings.php

Please change it [here](https://github.com/deitch/Codiad-CodeGit/blob/lock-down-git-user/README.md#lock-git-user-to-login-user) too

> #27  

Merged

**Comment by deitch** [comment]
OK, fixed the whitespace and filename issue. 

I see you merged it in. This PR and the other one will conflict with each other. I will fix the other one with 0.6.0, you can merge it in, then I will fix this one.

**Comment by Andr3as** [comment]
Great, :+1:

**Comment by Andr3as** [comment]
Merges and cleanup are done. Master branch is ready…

**Comment by deitch** [comment]
Got it. Always a pain to do the rebase to master. git needs an easier way to do it.

**Comment by Andr3as** [comment]
Thank you for contributing

**Pull request merged**
